config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
from django.views.generic import RedirectView


urlpatterns = [
    # Django admin
    path('administration/doc/', include('django.contrib.admindocs.urls')),
    path('administration/', admin.site.urls),

    # Account management
    path('members/', include('django.contrib.auth.urls')),
    path('.well-known/change-password/', RedirectView.as_view(pattern_name='password_change')),


    # Local Apps
    path('committees/', include('committees.urls')),
    path('dens/', include('dens.urls')),
    path('documents/', include('documents.urls')),
    path('calendar/', include('pack_calendar.urls')),
    path('members/', include('membership.urls')),
    path('polls/', include('polls.urls')),
    path('', include('pages.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path(
          "400/",
          default_views.bad_request,
          kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
          "403/",
          default_views.permission_denied,
          kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
          "404/",
          default_views.page_not_found,
          kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        ] + urlpatterns

dens/urls.py
from django.urls import path

from .views import DenDetailView, DensListView

urlpatterns = [
    path('', DensListView.as_view(), name='dens_list'),
    path('<int:pk>/', DenDetailView.as_view(), name='den_detail'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:pk>/vote/', views.VoteView.as_view(), name='vote'),
]

polls/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from tinymce.models import HTMLField


def two_weeks_hence(when=timezone.now()):
    return when + timezone.timedelta(weeks=2)


class Question(models.Model):
    question_text = models.CharField(
        max_length=200,
    )
    description = HTMLField(
        blank=True,
        null=True,
    )
    poll_opens = models.DateTimeField(
        _("poll opens"),
        default=timezone.now,
        blank=True,
    )
    poll_closes = models.DateTimeField(
        _("poll closes"),
        default=two_weeks_hence,
        blank=True,
    )

    is_anonymous = models.BooleanField(
        _("anonymous"),
        default=False,
    )
    is_editable = models.BooleanField(
        _("editable"),
        default=True,
    )

    class Meta:
        ordering = ('-poll_closes', )

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse_lazy('polls:detail', kwargs={'pk': self.pk})

    def can_vote(self, member):
        if self.poll_opens <= timezone.now() <= self.poll_closes:
            return member.get_active_scouts().count() - self.vote_set.filter(
                family=member.family
            ).count()

    def count_choices(self):
        return self.choice_set.count()

    def count_total_votes(self):
        result = 0
        for choice in self.choice_set.all():
            result += choice.count_votes()
        return result

    def was_published_recently(self):
        now = timezone.now()
        return now - timezone.timedelta(days=1) <= self.poll_opens <= now

    was_published_recently.admin_order_field = 'poll_opens'
    was_published_recently.boolean = True
    was_published_recently.short_description = _("Recently published?")


class Choice(models.Model):
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
    )
    choice_text = models.CharField(
        max_length=200,
    )

    def __str__(self):
        return self.choice_text

    def count_votes(self):
        return self.vote_set.count()


class Vote(models.Model):
    family = models.ForeignKey(
        'membership.Family',
        on_delete=models.CASCADE,
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
    )
    choice = models.ForeignKey(
        Choice,
        on_delete=models.CASCADE,
    )

    date_added = models.DateTimeField(
        auto_now_add=True,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return f"Vote for {self.choice}"

polls/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, ListView, RedirectView

from membership.mixins import ActiveMemberOrContributorTest

from .models import Choice, Question, Vote


class IndexView(ActiveMemberOrContributorTest, ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            poll_opens__lte=timezone.now()
        ).filter(
            poll_closes__gt=timezone.now()
        )


class QuestionView(ActiveMemberOrContributorTest, DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['question'].votable = self.object.can_vote(self.request.user)
        context['question'].votes_cast = self.object.vote_set.filter(
            family=self.request.user.family
        ) if not self.object.is_anonymous else None

        if not context['question'].votable:
            context['error_title'] = _("You've voted")
            context['error_level'] = 'info'
            context['error_message'] = _(
                "You have already voted on this question. There is nothing "
                "more you need to do."
            )

        elif self.object.poll_opens > timezone.now():
            context['error_title'] = _("Please Wait")
            context['error_level'] = 'warning'
            context['error_message'] = _(
                f"This question will be available to answer at "
                f"{self.object.poll_opens}."
            )

        elif self.object.poll_closes <= timezone.now():
            context['error_title'] = _("Time's Up")
            context['error_level'] = 'warning'
            context['error_message'] = _(
                f"The deadline to submit responses was "
                f"{self.object.poll_opens}."
            )

        return context

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(
            poll_opens__lte=timezone.now()
        ).filter(
            poll_closes__gt=timezone.now()
        )


class ResultsView(ActiveMemberOrContributorTest, DetailView):
    model = Question
    template_name = 'polls/results.html'


class VoteView(ActiveMemberOrContributorTest, RedirectView):
    def post(self, request, *args, **kwargs):
        question = Question.objects.get(id=kwargs['pk'])
        family = request.user.family
        choice = Choice.objects.get(id=request.POST['choice'])
        Vote.objects.create(question=question, family=family, choice=choice)
        messages.success(request, _("Thank you for your vote"))
        return super(VoteView, self).post(request, *args, **kwargs)

    def get_redirect_url(self, **kwargs):
        return reverse_lazy('polls:detail', args=[kwargs['pk']])

polls/templates/polls/detail.html
{% extends '_base.html' %}

{% block title %}{{ question.question_text|truncatewords:5 }}{% endblock %}

{% block content %}
  <div class="card w-75">
    <div class="card-body">
      <h4 class="card-title">{{ question.question_text }}</h4>
      {% if question.description %}<p class="card-subtitle text-muted">{{ question.description|safe }}</p>{% endif %}
      {% if error_message %}
        <div class="alert alert-{{ error_level }}">
          <h4 class="alert-heading">{{ error_title }}</h4>
          <p>{{ error_message }}</p>
        </div>
      {% elif question.votable %}
        <div class="card-text">
          <div class="alert alert-light"><small>You have {{ question.votable }} vote{{ question.votable|pluralize }} available.</small></div>
          <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
              <div class="form-check">
                <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
              </div>
            {% endfor %}
            <input class="btn btn-primary mt-3" type="submit" value="Vote">
          </form>
        </div>
      {% endif %}
      {% for vote in question.vote_set.all %}
        {{ vote }}
      {% endfor %}
    </div>
  </div>
{% endblock content %}

polls/templates/polls/index.html
{% extends '_base.html' %}

{% block title %}Polls{% endblock %}

{% block content %}
  {% if latest_question_list %}
    <div class="list-group">
    {% for question in latest_question_list %}
      <a class="list-group-item list-group-item-action" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
    {% endfor %}
    </div>
    {% else %}
    <div class="alert alert-info">
      <h4 class="alert-heading">No polls are available</h4>
    </div>
  {% endif %}
{% endblock content %}

polls/templates/polls/results.html
{% extends '_base.html' %}

{% block title %}{{ question.question_text|truncatewords:5 }}{% endblock %}

{% block content %}
  <h1>{{ question.question_text }}</h1>

  <ul class="list-unstyled">
    {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }} — {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
  </ul>
{% endblock content %}