config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
from django.views.generic import RedirectView


urlpatterns = [
    # Django admin
    path('administration/doc/', include('django.contrib.admindocs.urls')),
    path('administration/', admin.site.urls),

    # Account management
    path('members/', include('django.contrib.auth.urls')),
    path('.well-known/change-password/', RedirectView.as_view(pattern_name='password_change')),


    # Local Apps
    path('committees/', include('committees.urls')),
    path('dens/', include('dens.urls')),
    path('documents/', include('documents.urls')),
    path('calendar/', include('pack_calendar.urls')),
    path('members/', include('membership.urls')),
    path('polls/', include('polls.urls')),
    path('', include('pages.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path(
          "400/",
          default_views.bad_request,
          kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
          "403/",
          default_views.permission_denied,
          kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
          "404/",
          default_views.page_not_found,
          kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        ] + urlpatterns

dens/urls.py
from django.urls import path

from .views import DenDetailView, DensListView

urlpatterns = [
    path('', DensListView.as_view(), name='dens_list'),
    path('<int:pk>/', DenDetailView.as_view(), name='den_detail'),
]

pages/models.py
import uuid
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.html import strip_tags
from django.utils.translation import gettext_lazy as _

from tinymce.models import HTMLField


class Category(models.Model):
    name = models.CharField(
        max_length=32,
    )

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    date_added = models.DateTimeField(
        auto_now_add=True,
        blank=True,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        indexes = [models.Index(fields=['name'])]
        ordering = ['name']
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name


class Page(models.Model):
    """
    Base model used to define a web page. Used by Dynamic and Static pages.
    """
    title = models.CharField(
        max_length=64,
    )

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    created_on = models.DateTimeField(
        auto_now_add=True,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        indexes = [models.Index(fields=['title'])]
        verbose_name = _("Page")
        verbose_name_plural = _("Pages")

    def __str__(self):
        return self.title


class DynamicPage(Page):
    """
    Model that can be used for any arbitrary page on the website.
    """
    categories = models.ManyToManyField(
        Category,
        related_name='dynamic_page',
        blank=True,
    )
    include_in_nav = models.BooleanField(
        _("Include in navigation"),
        default=False,
        help_text=_(
            "Checking this option will add this page to the site's menu bar."),
    )
    slug = models.SlugField(
        unique=True
    )

    class Meta:
        indexes = [models.Index(fields=['include_in_nav', 'slug'])]
        verbose_name = _("Dynamic Page")
        verbose_name_plural = _("Dynamic Pages")

    def get_absolute_url(self):
        return reverse_lazy('dynamic_page', kwargs={'slug': self.slug})


class StaticPage(Page):
    """
    Model used by the standard pages every site should contain.
    """
    HOME = 'HOME'
    ABOUT = 'ABOUT'
    HISTORY = 'HISTORY'
    SIGNUP = 'SIGNUP'
    PAGE_CHOICES = (
        (HOME, _("Home")),
        (ABOUT, _("About Us")),
        (HISTORY, _("History")),
        (SIGNUP, _("Join Us")),
    )
    page = models.CharField(
        max_length=8,
        choices=PAGE_CHOICES,
        unique=True,
    )

    class Meta:
        verbose_name = _("Static Page")
        verbose_name_plural = _("Static Pages")

    def __str__(self):
        return self.get_page_display()

    def get_absolute_url(self):
        if self.page == StaticPage.HOME:
            return reverse_lazy('home_page')
        elif self.page == StaticPage.ABOUT:
            return reverse_lazy('about_page')
        elif self.page == StaticPage.HISTORY:
            return reverse_lazy('history_page')


class Content(models.Model):
    """
    Pages can contain any number of content blocks. Each block has its own
    visibility, allowing for different content to be displayed based on whether
    a user is logged in and has permission.
    """
    PUBLIC = 'P'
    PRIVATE = 'S'
    ANONYMOUS = 'A'
    VISIBILITY_CHOICES = [
        (PUBLIC, _("Public")),
        (PRIVATE, _("Private")),
        (ANONYMOUS, _("Anonymous"))
    ]

    title = models.CharField(
        max_length=256,
        blank=True,
        null=True,
    )
    visibility = models.CharField(
        max_length=1,
        choices=VISIBILITY_CHOICES,
        default=PRIVATE,
        help_text=(
            "Private content will only be viewable to active members or "
            "contributors. Public content is viewable by anyone on the "
            "website, including applicants, alumni, and anonymous visitors. "
            "Anonymous content will be displayed if no user is logged-in."),
    )
    body = HTMLField()
    page = models.ForeignKey(
        Page,
        on_delete=models.CASCADE,
    )

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    date_added = models.DateTimeField(
        auto_now_add=True,
        blank=True,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
    )
    published_on = models.DateTimeField(
        default=timezone.now,
        blank=True,
        null=True,
    )

    def __str__(self):
        if self.title:
            return self.title
        else:
            return f"{strip_tags(self.body)[:25]}…"

    class Meta:
        indexes = [models.Index(fields=['title', 'published_on'])]
        ordering = ['-published_on']
        verbose_name = _("Content")
        verbose_name_plural = _("Content")

pages/templates/pages/about_page.html
{% extends '_base.html' %}

{% block title %}{% if page_content %}{{ page_content.title }}{% else %}About Us{% endif %}{% endblock %}

{% block content %}
  <h1>{% if page_content %}{{ page_content.title }}{% else %}About Us{% endif %}</h1>
  {% include 'pages/page_content_snippet.html' %}
{% endblock %}

pages/templates/pages/dynamicpage_detail.html
{% extends '_base.html' %}

{% block title %}{% if page_content %}{{ page_content.title }}{% else %}Hello World{% endif %}{% endblock %}

{% block content %}
  <h1>{% if page_content %}{{ page_content.title }}{% else %}Hello World{% endif %}</h1>
  {% include 'pages/page_content_snippet.html' %}
{% endblock %}

pages/templates/pages/dynamicpage_form.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ page_content.title }}{% endblock %}

{% block content %}
  <h1>Update {{ page_content.title }}</h1>
  <form method="post" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Update</button>
    <a class="btn btn-primary" href="{% url 'dynamic_page' page_content.slug %}">Cancel</a>
  </form>
{% endblock %}

pages/templates/pages/history_page.html
{% extends '_base.html' %}

{% block title %}{% if page_content %}{{ page_content.title }}{% else %}Our History{% endif %}{% endblock %}

{% block content %}
  <h1>{% if page_content %}{{ page_content.title }}{% else %}Our History{% endif %}</h1>
  {% include 'pages/page_content_snippet.html' %}
{% endblock %}

pages/templates/pages/home_page.html
{% extends '_base.html' %}

{% block title %}{% if page_content %}{{ page_content.title }}{% else %}Home{% endif %}{% endblock %}

{% block content %}
  <h1>{% if page_content %}{{ page_content.title }}{% else %}Home{% endif %}</h1>
  {% if event_list %}
    <div class="mt-5">
      <h3>Coming Up</h3>
      {% include 'pack_calendar/events_list_snippet.html' %}
    </div>
  {% endif %}
  {% include 'pages/page_content_snippet.html' %}
{% endblock %}

pages/templates/pages/page_content_snippet.html
  {% for content in page_content.content_set.all %}
    {% if content.visibility == 'S' and request.user.active or content.visibility == 'P' or content.visibility == 'A' and not request.user.is_authenticated %}
    <div class="mt-5">
      {% if content.title %}<h3>{{ content.title }}</h3>{% endif %}
    {{ content.body|safe }}
    </div>
    {% endif %}
  {% empty %}
    <div class="alert alert-warning" role="alert">This page has no content yet. Here is some sample text to give you a feel for what this page will look like with content</div>
    {% lorem 5 p %}
  {% endfor %}

pages/templates/pages/signup_page.html
{% extends '_base.html' %}
{% load crispy_forms_tags static %}

{% block title %}{% if page_content %}{{ page_content.title }}{% else %}Sign Up{% endif %}{% endblock %}

{% block content %}
  <h1>{% if page_content %}{{ page_content.title }}{% else %}Sign Up {% endif %}</h1>
  {% include 'pages/page_content_snippet.html' %}
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="mt-3" id="personal-details">
          {% crispy form %}
        </fieldset>
        <fieldset class="mt-5" id="{{ address_formset.prefix }}">
          <legend>Address{{ address_formset.total_form_count|pluralize:'es' }}</legend>
          {{ address_formset.management_form|crispy }}
          {% for form in address_formset.forms %}
            {% crispy form %}
          {% endfor %}
        </fieldset>
        <fieldset class="mt-5" id="{{ phonenumber_formset.prefix }}">
          <legend>Phone Number{{ phonenumber_formset.total_form_count|pluralize }}</legend>
          {{ phonenumber_formset.management_form|crispy }}
          {% for form in phonenumber_formset.forms %}
            {% crispy form %}
          {% endfor %}
        </fieldset>
        <div class="row justify-content-end mt-5">
          <input type="submit" value="Sign me up!" class="btn btn-success btn-lg btn-block"/>
        </div>
      </form>

{% endblock content %}

{% block js %}
  <script src="{% static "dynamic_formsets/jquery.formset.js" %}" type="text/javascript"></script>
  <script type="text/javascript">
      $('#{{ address_formset.prefix }}').formset({
          addCssClass: "btn btn-primary btn-sm",
          deleteCssClass: 'btn btn-danger align-self-start',
          formCssClass: 'address-dynamic-form',
          prefix: "{{ address_formset.prefix }}",
          uiText: {
              addPrompt: "<i class=\"fas fa-plus-circle mr-1\"></i> address",
              removePrompt: "<i class=\"fas fa-trash-alt\"></i>"
          },
      });
      $('#{{ phonenumber_formset.prefix }}').formset({
          addCssClass: "btn btn-primary btn-sm",
          deleteCssClass: 'btn btn-danger align-self-start',
          formCssClass: 'phonenumber-dynamic-form',
          prefix: "{{ phonenumber_formset.prefix }}",
          uiText: {
              addPrompt: "<i class=\"fas fa-plus-circle mr-1\"></i> phone number",
              removePrompt: "<i class=\"fas fa-trash-alt\"></i>"
          },
      });
  </script>
{% endblock js %}