config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
from django.views.generic import RedirectView


urlpatterns = [
    # Django admin
    path('administration/doc/', include('django.contrib.admindocs.urls')),
    path('administration/', admin.site.urls),

    # Account management
    path('members/', include('django.contrib.auth.urls')),
    path('.well-known/change-password/', RedirectView.as_view(pattern_name='password_change')),


    # Local Apps
    path('committees/', include('committees.urls')),
    path('dens/', include('dens.urls')),
    path('documents/', include('documents.urls')),
    path('calendar/', include('pack_calendar.urls')),
    path('members/', include('membership.urls')),
    path('polls/', include('polls.urls')),
    path('', include('pages.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path(
          "400/",
          default_views.bad_request,
          kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
          "403/",
          default_views.permission_denied,
          kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
          "404/",
          default_views.page_not_found,
          kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        ] + urlpatterns

dens/urls.py
from django.urls import path

from .views import DenDetailView, DensListView

urlpatterns = [
    path('', DensListView.as_view(), name='dens_list'),
    path('<int:pk>/', DenDetailView.as_view(), name='den_detail'),
]

documents/models.py
import uuid
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


def document_upload_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/documents/category_slug/<filename>
    return f"documents/{slugify(instance.category)}/{filename}"


class Category(models.Model):
    name = models.CharField(
        max_length=32,
    )

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    date_added = models.DateField(
        auto_now_add=True,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")


class Document(models.Model):
    name = models.CharField(
        max_length=128,
    )
    description = models.TextField(
        blank=True,
        null=True,
        help_text=_("Brief description of what the document is."),
    )
    file = models.FileField(
        upload_to=document_upload_path,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='documents',
    )
    committee = models.ForeignKey(
        'committees.Committee',
        on_delete=models.SET_NULL,
        related_name='documents',
        blank=True,
        null=True,
    )
    display_in_repository = models.BooleanField(
        default=True,
        help_text=_("Make this document visible in the Document Repository"),
    )

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    date_added = models.DateField(
        auto_now_add=True,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['category', 'name', ]
        verbose_name = _("Document")
        verbose_name_plural = _("Documents")

    def get_file_type(self):
        extension = self.file.file.split('.')[-1]
        if extension in ('txt', 'rtf'):
            return _("Text Document")
        elif extension in ('pdf', ):
            return _("PDF")
        elif extension in ('doc', 'docx'):
            return _("Microsoft Word Document")
        elif extension in ('xls', 'xlsx'):
            return _("Microsoft Excel Spreadsheet")
        elif extension in ('ppt', 'pptx', 'pps', 'ppsx'):
            return _("Microsoft Powerpoint Presentation")
        elif extension in ('jpg', 'jpeg', 'gif', 'png', 'tiff', 'bmp'):
            return _("Image")
        elif extension in ('mp4', 'm4v', 'ogv', 'webm', 'mov'):
            return _("Video")
        elif extension in ('wav', 'wave', 'mp3', 'ogg', 'oga', 'ogm', 'spx', 'opus'):
            return _("Audio")
        elif extension in ('zip', ):
            return _("Compressed Archive")

membership/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from easy_thumbnails.fields import ThumbnailerImageField
from easy_thumbnails.signal_handlers import generate_aliases
from easy_thumbnails.signals import saved_file

from dens.models import Den
from pack_calendar.models import PackYear
from .managers import MemberManager, ScoutManager


def get_photo_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/headshots/user_slug/<filename>
    return f"headshots/{instance.slug}/{filename}"


def get_two_years_ago():
    """
    Calculate the year two years before the current year.
    Used by the Scout model to provide a default for when they start school.
    """
    return timezone.now().year - 2


class Member(models.Model):
    """
    A class implementing the details we would want to capture for any person.
    Used by the later models, Adult and Scout, to populate common fields used.
    """

    # Define static options for gender
    MALE = 'M'
    FEMALE = 'F'
    OTHER = 'O'
    GENDER_CHOICES = (
        (MALE, _("Male")),
        (FEMALE, _("Female")),
        (OTHER, _("Prefer not to say"))
    )

    # Personal information
    first_name = models.CharField(
        _("First Name"),
        max_length=30
    )
    middle_name = models.CharField(
        _("Middle Name"),
        max_length=32,
        blank=True,
        null=True
    )
    last_name = models.CharField(
        _("Last Name"),
        max_length=150
    )
    suffix = models.CharField(
        _("Suffix"),
        max_length=8,
        blank=True,
        null=True
    )
    nickname = models.CharField(
        _("Nickname"),
        max_length=32,
        blank=True,
        null=True,
        help_text=_(
            "If there is another name you prefer to be called, tell us and we "
            "will use it any time we refer to you on the website.")
    )
    gender = models.CharField(
        _("Gender"),
        max_length=1,
        choices=GENDER_CHOICES,
        default=None,
        blank=False,
        null=True
    )
    photo = ThumbnailerImageField(
        _("Headshot Photo"),
        upload_to=get_photo_path,
        blank=True,
        null=True,
        help_text=_(
            "We use member photos on the website to help match names with "
            "faces.")
    )
    date_of_birth = models.DateField(
        _("Birthday"),
        blank=True,
        null=True
    )

    # Administrative
    slug = models.SlugField(
        unique=True,
        blank=True,
        null=True
    )
    pack_comments = models.TextField(
        _("Pack Comments"),
        blank=True,
        null=True,
        help_text=_(
            "Used by pack leadership to keep notes about a specific member. "
            "This information is not generally disclosed to the member unless "
            "they are granted access to Membership.")
    )

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    date_added = models.DateTimeField(
        auto_now_add=True,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        indexes = [models.Index(fields=[
            'first_name',
            'middle_name',
            'nickname',
            'last_name',
            'gender'
        ])]
        ordering = ['last_name', 'nickname', 'first_name']

    def __str__(self):
        return self.get_full_name()

    def save(self, *args, **kwargs):
        if not self.slug:
            candidates = [self.get_full_name()]
            if self.middle_name and self.suffix:
                candidates.append(
                    f"{self.first_name} "
                    f"{self.middle_name[0]} "
                    f"{self.last_name} "
                    f"{self.suffix}"
                )
                candidates.append(
                    f"{self.first_name} "
                    f"{self.middle_name} "
                    f"{self.last_name} "
                    f"{self.suffix}"
                )
            elif self.suffix:
                candidates.append(
                    f"{self.first_name} "
                    f"{self.last_name} "
                    f"{self.suffix}"
                )
            elif self.middle_name:
                candidates.append(
                    f"{self.first_name} "
                    f"{self.middle_name[0]} "
                    f"{self.last_name}"
                )
                candidates.append(
                    f"{self.first_name} "
                    f"{self.middle_name} "
                    f"{self.last_name}"
                )
            self.choose_slug(candidates=candidates)
            if not self.slug:
                # None of the normal candidates seem to have worked or we would
                # have a slug now. Start adding digits to the end of their name
                candidates = [f"{self.get_full_name()} {i}" for i in
                              range(1, 100)]
                self.choose_slug(candidates=candidates)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        if hasattr(self, 'adult'):
            return reverse('parent_detail', kwargs={'slug': self.slug})
        elif hasattr(self, 'scout'):
            return reverse('scout_detail', kwargs={'slug': self.slug})
        else:
            return None

    def get_full_name(self):
        """
        Return the short name, either first_name or nickname, plus the
        last_name, with a space in between.
        """
        if self.suffix:
            return f"{self.get_short_name()} {self.last_name} {self.suffix}"
        else:
            return f"{self.get_short_name()} {self.last_name}"

    def get_short_name(self):
        """ Return either the first_name or nickname for the member. """
        return self.nickname if self.nickname else self.first_name

    def choose_slug(self, candidates):
        for candidate in candidates:
            if not Member.objects.filter(slug=slugify(candidate)):
                self.slug = slugify(candidate)
                break
        return self.slug

    def age(self):
        """ If we have a birthday, calculate the current age of the member. """
        if self.date_of_birth:
            today = timezone.now()
            return today.year - self.date_of_birth.year - (
                # This will calculate a 1 if the date hasn't come yet this year
                    (today.month, today.day) <
                    (self.date_of_birth.month, self.date_of_birth.day)
            )

    age.admin_order_field = 'date_of_birth'


class Family(models.Model):
    """ Track the relationship between members """
    name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
    )

    pack_comments = models.TextField(
        _("Pack Comments"),
        blank=True,
        null=True,
        help_text=_(
            "Used by pack leadership to keep notes about a specific family. "
            "This information is not generally disclosed to members unless "
            "they are granted access to Membership."),
    )

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    legacy_id = models.PositiveSmallIntegerField(
        unique=True,
        blank=True,
        null=True,
    )
    date_added = models.DateField(
        auto_now_add=True,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        indexes = [models.Index(fields=['name'])]
        ordering = ['date_added']
        verbose_name = _("Family")
        verbose_name_plural = _("Families")

    def __str__(self):
        if self.name:
            return self.name

    def save(self, *args, **kwargs):
        last_names = []
        for parent in self.adults.all():
            if parent.last_name not in last_names:
                last_names.append(parent.last_name)
        self.name = "-".join(last_names) + " Family"
        return super().save(*args, **kwargs)


class Adult(AbstractBaseUser, PermissionsMixin, Member):
    """
    Any adult member such as a parent, guardian, or other use this model. Being
    an adult gives you access to the website with an e-mail address and
    password.
    """

    # Define the various roles an adult member can have within the Pack
    PARENT = 'P'
    GUARDIAN = 'G'
    CONTRIBUTOR = 'C'
    ROLE_CHOICES = (
        (PARENT, _("Parent")),
        (GUARDIAN, _("Guardian")),
        (CONTRIBUTOR, _("Friend of the Pack")),
    )

    email = models.EmailField(
        _('Email Address'),
        unique=True
    )
    is_published = models.BooleanField(
        _('Published'),
        default=True,
        help_text=_("Display this address to other members of the pack."),
    )

    role = models.CharField(
        _('Role'),
        max_length=1,
        choices=ROLE_CHOICES,
        default=PARENT,
    )
    family = models.ForeignKey(
        Family,
        on_delete=models.CASCADE,
        related_name='adults',
        blank=True,
        null=True,
    )

    objects = MemberManager()
    _is_staff = models.BooleanField(
        _("Staff"),
        default=False,
        help_text=_(
            "Designates whether the user can log into this admin site."
        ),
    )
    is_active = models.BooleanField(
        _("Active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:

templates/403_csrf.html
{% extends "_base.html" %}

{% block title %}403 Forbidden{% endblock title %}

{% block content %}
  <div class="alert alert-danger" role="alert">
    <h1 class="alert-heading">{{ title }} <span>(403)</span></h1>
    <p>{{ main }}</p>
    {% if no_referer %}
      <p>{{ no_referer1 }}</p>
      <p>{{ no_referer2 }}</p>
      <p>{{ no_referer3 }}</p>
    {% endif %}
    {% if no_cookie %}
      <p>{{ no_cookie1 }}</p>
      <p>{{ no_cookie2 }}</p>
    {% endif %}
  </div>
{% endblock %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '@forevolve/bootstrap-dark/dist/css/bootstrap-dark.min.css' %}" media="screen and (prefers-color-scheme: dark)">
  <link rel="stylesheet" href="{% static '@fortawesome/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/packman.css' %}">

  {% block css %}{% endblock %}
  <title>Pack 144: {% block title %}Hello World!{% endblock %}</title>
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'icons/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'icons/safari-pinned-tab.svg' %}" color="#de2d2d">
  <link rel="shortcut icon" href="{% static 'icons/favicon.ico' %}">
  <meta name="apple-mobile-web-app-title" content="Pack 144">
  <meta name="application-name" content="Pack 144">
  <meta name="msapplication-TileColor" content="#5b5d8a">
  <meta name="msapplication-config" content="{% static 'icons/browserconfig.xml' %}">
  <meta name="theme-color" content="#5b5d8a">
</head>

<body class="d-flex flex-column h-100">
<header>
  <div class="jumbotron">
    <a class="navbar-brand" href="{% url 'home_page' %}">
      <div class="row align-items-center">
        <div class="col d-none d-sm-block">
          <img src="{% static 'img/logo.png' %}" width="125" height="70" class="d-inline align-top" alt="Pack Logo">
        </div>
        <div class="col d-block d-sm-none">
          <img src="{% static 'img/logo.png' %}" width="64" height="36" class="d-inline align-top" alt="Pack Logo">
        </div>
        <div class="col d-none d-sm-block">
          <div class="row" id="pack-name">{{ pack_name }}</div>
          <div class="row" id="pack-location">{{ pack_location }}</div>
          <div class="row" id="pack-tagline">{{ pack_tagline }}</div>
        </div>
      </div>
    </a>
  </div>
  {% block navbar %}
    <div class="navbar sticky-top navbar-expand-lg navbar-dark" id="top-bar">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
              aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarContent">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link mr-lg-3{% if request.resolver_match.url_name == 'home_page' %} active{% endif %}" href="{% url 'home_page' %}">Home</a>
          {% if user.is_authenticated %}
            <a class="nav-item nav-link mr-lg-3{% if request.resolver_match.url_name == 'event_list' %} active{% endif %}" href="{% url 'event_list' %}">Calendar</a>
            <a class="nav-item nav-link mr-lg-3{% if request.resolver_match.url_name == 'member_list' %} active{% endif %}" href="{% url 'member_list' %}">Members</a>
            <a class="nav-item nav-link mr-lg-3{% if request.resolver_match.url_name == 'committees_list' %} active{% endif %}" href="{% url 'committees_list' %}">Committees</a>
            <a class="nav-item nav-link mr-lg-3{% if request.resolver_match.url_name == 'document_list' %} active{% endif %}" href="{% url 'document_list' %}">Documents</a>
            {% for item in private_pages %}
              <a class="nav-item nav-link mr-lg-3{% if request.resolver_match.url_name == 'dynamic_page' and request.resolver_match.kwargs.slug == item.slug %} active{% endif %}" href={% url 'dynamic_page' item.slug %}>{{ item }}</a>
            {% endfor %}
          {% endif %}
          {% for item in public_pages %}
            <a class="nav-item nav-link mr-lg-3{% if request.resolver_match.url_name == 'dynamic_page' and request.resolver_match.kwargs.slug == item.slug %} active{% endif %}" href={% url 'dynamic_page' item.slug %}>{{ item }}</a>
          {% endfor %}
          <a class="nav-item nav-link mr-lg-3{% if request.resolver_match.url_name == 'about_page' %} active{% endif %}" href="{% url 'about_page' %}">About Us</a>
          <a class="nav-item nav-link mr-lg-3{% if request.resolver_match.url_name == 'history_page' %} active{% endif %}" href="{% url 'history_page' %}">Our History</a>
        </div>
        <ul class="navbar-nav ml-auto">{% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-warning" href="#" id="navbarMemberDropdown" role="button"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
              {{ user.get_short_name }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarMemberDropdown">
              <a class="dropdown-item" href="{% url 'family_update' %}">My Family</a>
              <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
              {% if user.is_staff %}<a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>{% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item text-danger" href="{% url 'logout' %}">Log out</a>
            </div>
          </li>{% else %}
          <li class="nav-item">
            <a class="nav-link mr-lg-3" href="{% url 'signup' %}">Join Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-success" href="{% url 'login' %}?next={{ request.path }}">Sign in</a>
          </li>{% endif %}
        </ul>
      </div>
    </div>
  {% endblock navbar %}
</header>

<main role="main" class="flex-shrink-0">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        {% block content %}<h1>Hello World!</h1>{% endblock %}

        {% if is_paginated %}
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item d-block">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link"><i class="far fa-arrow-alt-circle-left"><span class="sr-only">Next</span></i></a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" aria-disabled="true"><i class="far fa-arrow-alt-circle-left"></i></a></li>
            {% endif %}
            {% for page in paginator.page_range %}
              {% if page_obj.number == page %}
                <li class="page-item active">
                  <a class="page-link" href="#" aria-disabled="true">{{ page }} <span class="sr-only">(current)</span>
                    <span class="d-lg-none"> of {{ paginator.num_pages }}</span>
                  </a></li>
              {% else %}
                <li class="page-item d-none d-lg-block"><a href="?page={{ page }}" class="page-link">{{ page }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}" class="page-link"><i class="far fa-arrow-alt-circle-right"><span class="sr-only">Next</span></i></a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" aria-disabled="true"><i class="far fa-arrow-alt-circle-right"></i></a>
              </li>
            {% endif %}
          </ul>
        {% endif %}
      </div>
    </div>
  </div>
</main>

<footer class="footer mt-auto py-3">
  <div class="container">
    <p>A scout is trustworthy, loyal, helpful, friendly, courteous, kind, obedient, cheerful, thrifty, brave, clean, and reverent.</p>
  </div>
</footer>

<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'popper.js/dist/umd/popper.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/_base_wo_nav.html
{% extends '_base.html' %}

{% block navbar %}{% endblock %}