committees/urls.py
from django.urls import path

from .views import CommitteeDetail, CommitteesList


urlpatterns = [
    path(
        '',
        CommitteesList.as_view(),
        name='committees_list'
    ),
    path(
        '<int:year>/',
        CommitteesList.as_view(),
        name='committees_list_by_year'
    ),
    path(
        '<slug:slug>/',
        CommitteeDetail.as_view(),
        name='committee_detail'
    ),
    path(
        '<slug:slug>/<int:year>/',
        CommitteeDetail.as_view(),
        name='committee_detail_by_year'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
from django.views.generic import RedirectView


urlpatterns = [
    # Django admin
    path('administration/doc/', include('django.contrib.admindocs.urls')),
    path('administration/', admin.site.urls),

    # Account management
    path('members/', include('django.contrib.auth.urls')),
    path('.well-known/change-password/', RedirectView.as_view(pattern_name='password_change')),


    # Local Apps
    path('committees/', include('committees.urls')),
    path('dens/', include('dens.urls')),
    path('documents/', include('documents.urls')),
    path('calendar/', include('pack_calendar.urls')),
    path('members/', include('membership.urls')),
    path('polls/', include('polls.urls')),
    path('', include('pages.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path(
          "400/",
          default_views.bad_request,
          kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
          "403/",
          default_views.permission_denied,
          kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
          "404/",
          default_views.page_not_found,
          kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        ] + urlpatterns

dens/urls.py
from django.urls import path

from .views import DenDetailView, DensListView

urlpatterns = [
    path('', DensListView.as_view(), name='dens_list'),
    path('<int:pk>/', DenDetailView.as_view(), name='den_detail'),
]

committees/models.py
import uuid
from django.contrib.auth.models import Group
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from pack_calendar.models import PackYear


class Committee(models.Model):
    """
    A well run pack relies on its members stepping up to provide support.
    Define a list of ongoing committees on which Adults can offer their
    services to assist with pack operations.
    """
    name = models.CharField(
        max_length=64,
    )
    description = models.TextField(
        null=True,
        blank=True,
    )
    members = models.ManyToManyField(
        'membership.Adult',
        through='Membership',
    )
    leadership = models.BooleanField(
        _("Pack Leadership"),
        default=False,
        help_text=_("e.g. Akela, Assistant Akela, Den Leader"),
    )
    is_staff = models.BooleanField(
        _("Staff"),
        default=False,
        help_text=_("Designates whether members can log into this admin site.")
    )
    slug = models.SlugField(
        unique=True,
    )

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    date_added = models.DateTimeField(
        auto_now_add=True,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        ordering = ['-leadership', 'name']
        verbose_name = _("Committee")
        verbose_name_plural = _("Committees")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('committee_detail', args=[self.slug])


class Membership(models.Model):
    """
    Tracks members who have signed up for a committee, the year of their
    service, and their position on the committee.
    """
    CHAIR = 1
    MEMBER = 2
    APPRENTICE = 3
    DEN_LEADER = 4
    AKELA = 5
    ASSISTANT_AKELA = 6
    POSITION_CHOICES = [
        (CHAIR, _("Chair")),
        (MEMBER, _("Member")),
        (APPRENTICE, _("Apprentice")),
        (DEN_LEADER, _("Den Leader")),
        (AKELA, _("Akela")),
        (ASSISTANT_AKELA, _("Assistant Akela")),
    ]

    member = models.ForeignKey(
        'membership.Adult',
        on_delete=models.CASCADE,
        related_name='committees',
    )
    committee = models.ForeignKey(
        Committee,
        on_delete=models.CASCADE,
    )
    position = models.PositiveSmallIntegerField(
        choices=POSITION_CHOICES,
        default=MEMBER,
    )
    den = models.ForeignKey(
        'dens.Den',
        on_delete=models.CASCADE,
        related_name='leadership',
        blank=True,
        null=True,
        help_text=_(
            "If the member is a Den Leader, which Den # are they supporting?"
        ),
    )
    year_served = models.ForeignKey(
        PackYear,
        on_delete=models.CASCADE,
        default=PackYear.get_current_pack_year_year,
        related_name='committee_memberships',
    )

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    date_added = models.DateTimeField(
        auto_now_add=True,
    )
    last_updated = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        ordering = ['year_served', 'den', 'position', 'member']
        verbose_name = _("Member")
        verbose_name_plural = _("Members")

    def __str__(self):
        return f"{self.member} {self.year_served}"

    def save(self, *args, **kwargs):
        group, created = Group.objects.get_or_create(name=self.committee.name)
        if group not in self.member.groups.all():
            self.member.groups.add(group)
        super(Membership, self).save(*args, **kwargs)

committees/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from membership.mixins import ActiveMemberOrContributorTest
from pack_calendar.models import PackYear
from . import models


class CommitteesList(LoginRequiredMixin, generic.ListView):
    """
    Display a list of Committees with members assigned for any given year. If
    no year is supplied, then display the current committees list based on the
    Pack Year as defined in settings.py.
    """
    model = models.Committee
    paginate_by = 50
    template_name = 'committees/committees_list.html'

    def get_queryset(self):
        year = PackYear.objects.get(
            year=PackYear.get_pack_year(self.kwargs['year'])['end_date'].year
        ) if 'year' in self.kwargs else PackYear.get_current_pack_year()
        return models.Committee.objects.filter(
            membership__year_served=year
        ).distinct()


class CommitteeDetail(ActiveMemberOrContributorTest, generic.DetailView):
    model = models.Committee
    template_name = 'committees/committee_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = PackYear.objects.get(
            year=PackYear.get_pack_year(self.kwargs['year'])['end_date'].year
        ) if 'year' in self.kwargs else PackYear.get_current_pack_year()
        all_years = PackYear.objects.filter(
            committee_memberships__committee=context['committee']).distinct()
        context['current_year'] = year
        context['all_years'] = all_years
        context['members'] = models.Membership.objects.filter(
            committee=context['committee'],
            year_served=year,
            position__lt=models.Membership.AKELA,
        )
        context['akelas'] = models.Membership.objects.filter(
            committee=context['committee'],
            year_served=year,
            position__gte=models.Membership.AKELA,
        )
        return context

committees/templates/committees/committee_detail.html
{% extends '_base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}{{ committee }}{% endblock %}

{% block content %}
  <div class="container rounded">
    <div class=" d-flex justify-content-between align-items-center">
      <h1>{{ committee }}</h1>
      <div class="btn-group">
        <button type="button" class="btn btn-secondary">{{ current_year }}</button>
        <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          {% for year in all_years %}
            {% if not year == current_year %}
              <a class="dropdown-item" href="{% url 'committee_detail_by_year' slug=committee.slug year=year.year %}">{{ year }}</a>
            {% else %}
              <div class="dropdown-item active">{{ year }}</div>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
    {% if committee.description %}<p class="text-muted">{{ committee.description }}</p>{% endif %}
  </div>

  <div class="container">
  {% if members.count %}
    <h2 class="mt-3">Member{{ members.count|pluralize }}</h2>
    <div class="list-group">
      {% for member in members.all %}
          <a class="list-group-item list-group-item-action" href="{{ member.member.get_absolute_url }}">
            <div class="row align-items-center">
              <div class="col-sm-3 col-lg-2">
                {% include 'membership/snippets/headshot_thumbnail_snippet.html' with member=member.member %}
              </div>
              <div class="col">
                <strong>{{ member.member }}</strong><br>
                <span class="text-muted">
                  {% if member.position == 4 %}
                    {{ member.den }}
                  {% else %}
                    {{ member.get_position_display }}
                  {% endif %}
                </span>
              </div>
            </div>
          </a>
      {% endfor %}
    </div>
  {% endif %}

  {% if akelas %}
    {% if not 'Akela' in committee.name %}<h2 class="mt-3">Supporting Akela{{ akelas.count|pluralize }}</h2>{% endif %}
    <div class="list-group">
      {% for member in akelas.all %}
          <a class="list-group-item list-group-item-action" href="{{ member.member.get_absolute_url }}">
            <div class="row align-items-center">
              <div class="col-sm-3 col-lg-2">
                {% include 'membership/snippets/headshot_thumbnail_snippet.html' with member=member.member %}
              </div>
              <div class="col">
                <strong>{{ member.member }}</strong><br>
              </div>
            </div>
          </a>
      {% endfor %}
    </div>
  {% endif %}
  </div>

{% endblock %}

committees/templates/committees/committees_list.html
{% extends '_base.html' %}

{% block title %}Committees{% endblock title %}

{% block content %}
  <div class="container row">
    <h1>Committees</h1>
  </div>
  <div class="container" id="committee-list">
  {% if committee_list %}
    <div class="list-group">
      {% for committee in committee_list %}
          <a class="list-group-item list-group-item-action" href="{{ committee.get_absolute_url }}">
            <div class="row">
              <div class="col-md-3 font-weight-bold ">{% if committee.leadership %}<i class="fas fa-star text-warning"></i> {% endif %}{{ committee }}</div>
              {% if committee.description %}<div class="col text-truncate"><small class="text-muted ml-3">{{ committee.description }}</small></div>{% endif %}
            </div>
          </a>
      {% endfor %}
    </div>
  {% else %}
    <div class="alert alert-light" role="alert">No committees have been defined yet</div>
  {% endif %}
  </div>
{% endblock %}